using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Controls;

namespace MongoMS.Find.Addin.Controls
{
   public class BsonDocumentDataGrid:DataGrid
    {
       protected override void OnAutoGeneratingColumn(DataGridAutoGeneratingColumnEventArgs e)
       {
          
       }

       protected override void OnAutoGeneratedColumns(EventArgs e)
       {
           
       }
    }
}
